services:
  mangaloidedb:
    image: mongo:latest
    container_name: mangaloidedb
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
  mangaloide:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mangaloide
    ports:
      - "80:3000"
    environment:
      - MONGO_URL=mongodb://mangaloidedb:27017/mangaloidedb
      - COMICS_PATH=./comics
      - TMP_PATH=./tmp
      - USERIMG_PATH=./userimages
      - JWT_SECRET_SEED=prova
