services:
  mangaloidedb:
    image: mongo:latest
    container_name: mangaloidedb
    ports:
      - 27017:27017
    volumes:
      - ../../mongo:/data/db
  mangaloide:
    container_name: mangaloideapp
    build:
      context: ../../
      dockerfile: ./docker/prod/Dockerfile
    image: mangaloide
    ports:
      - "80:3000"
    volumes:
      - ../../comics:/app/comics
      - ../../tmp:/app/tmp
      - ../../userimages:/app/userimages
