export enum Tag {
  Action = "action",
  Adventure = "adventure",
  Comedy = "comedy",
  Drama = "drama",
  Ecchi = "ecchi",
  Fantasy = "fantasy",
  Horror = "horror",
  MahouShoujo = "mahou shoujo",
  Mecha = "mecha",
  Music = "music",
  Mystery = "mystery",
  Psychological = "psychological",
  Romance = "romance",
  SciFi = "schi-fi",
  SliceOfLife = "slice of life",
  Sports = "sports",
  Supernatural = "supernatural",
  Thriller = "thriller",
}
